### ISSUE TITLE
Pre-processing of your En-Pd dataset.

### ISSUE THREAD

**Issue by kr-sundaram** [keleog/finetune_huggingace_t5#2]
Just want to be sure how you pre-processed your data set. Mainly on how much max_length have you considered and whether you removed some pairs which has ration of length of source to target more than 1.5?

**Comment by keleog** [comment]
My maximum input length was set at 512. I did not have to remove any
sentence pairs because my data had fairly similar sentence lengths.

**Comment by keleog** [comment]
Closing this now for lack of activity.
